language: node_js
node_js:
  - 8.10.0
  - 10
  - 11
os:
  - windows
  - osx
  - linux
dist: xenial
script: npm test
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    # - stage: Coverage check
    #   os: linux
    #   node_js: 11
    #   script: gulp coverage
    #   # If CI fails, codecov does not post a bot comment on PR, so we skip it
    #   if: type != pull_request && (branch == master || tag is not blank)
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`
    - stage: Deploy
      os: linux
      node_js: 11
      # We have already run tests
      script: gulp build
      if: tag is not blank
      # We run `release-it` locally (which tagged the commit and create a
      # GitHub release) but we publish to npm only after CI success.
      deploy:
        provider: npm
        email: ehmicky@gmail.com
        api_key:
          secure: dMh0zkLZSchnQ5B8xHzj5lIbjdI7P10Rt4Q0PN8p6XFOHiolavY5ofZTuCAO0HM7aLyYh+6jv0uy5h4LUKhKHfejPM2mg92JaidB5SNlktcIL+6rkGoc3mHwr/lYWD1tDCyDozGhY+6RHki6mMsGX3ByJCpQ8pSd+SaQ+S882j7Ot0lQ+Wh80IPEJw+/YN8Iv/LNtDYM3IV5YHYdex4iWu32Hz+B4gTOeYntdIJ0irod8UBkGEODK+6leEsraTWB0EtPRBzXfjwrjwq9Nh3zgwmbdt2iAgpz8wahSH+/5HC2haU7wfeg32fA4YfKJPiiriuEUfkpCkdsZHCtUOpRaAb69HJZNyiUVi4sFPuNzt+/bWvjE6134/JtyWUiF3KOrqHbyCuCsOTWrYK3kZF2dE+4N1ygVSWU3mlahIskslv21H3gaSOl5ZNqqEm9S25pMNqZ7+cZd2SxMKIRhzAqTXsPnsc5JielA8TyXaM/vHvzfEsEw1sECIaUEfqihteNtqeJv2AZQKYJt76T0S016XRdntKp3g6Ghg2RaqeT+pUP+YRISQSxnOjK7MuuEzD4wM69ecBUvkmtFU3qzeIay9fYfdXgPG9bqId/ktAYXsTcRIU/nv7BvB6gjaa2tBY/p0OoZ/SaQLacDYNHwClVLtYnZaYVeKnFS/B2jmfZ0pM=
        on:
          tags: true
        # We want to run install step and keep built files for release
        skip_cleanup: true
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
